# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_post_list:
    pattern: /
    defaults:
        _controller: sylius_blogger.controller.post:indexAction
        _template: SyliusSandboxBundle:Frontend/Post:list.html.twig
        _paginate: 10
        _criteria:
            published: true
        _sorting:
            createdAt: desc

sylius_sandbox_post_show:
    pattern: /{slug}
    defaults:
        _controller: sylius_blogger.controller.post:showAction
        _template: SyliusSandboxBundle:Frontend/Post:show.html.twig
        _identifier: slug
