imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: database.yml }

framework:
    default_locale:  %locale%
    form: ~
    secret:          %secret%
    csrf_protection:
        enabled: true
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    validation:      { enabled: true, enable_annotations: true }
    translator:      { fallback: %locale% }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    session:
        name: WN_SESSION
        lifetime: 72000


# Twig Configuration
twig:
    form:
        resources:
            - 'FreeNoteBundle::forms.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        currency:     %currency%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %fn_web_dir%

# Swiftmailer Configuration
swiftmailer:
    disable_delivery: %kernel.debug%
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

stof_doctrine_extensions:
    default_locale: %locale%
    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:       %fn_web_dir%/uploads/images
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true
            blameable: true
            uploadable: true

avalanche_imagine:
    source_root:  %fn_web_dir%
    web_root: %fn_web_dir%
    cache_prefix: media/cache
    filters:
        icon:
            type: thumbnail
            options: { size: [45, 30], mode: inbound }
        frontend_medium:
            type: thumbnail
            options: { size: [220, 180], mode: outbound }
        frontend_box:
            type: thumbnail
            options: { size: [130, 75], mode: outbound }
        backend_mini:
            type: thumbnail
            options: { size: [90, 60], mode: outbound }
        backend_medium:
            type: thumbnail
            options: { size: [250, 150], mode: outbound }

# User bundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: FreeNote\FreeNoteBundle\Entity\User
    registration:
        form:
            type: free_note_user_registration
            handler: free_note.user.registration.form.handler

fos_comment:
    db_driver: orm
    class:
        model:
            comment: FreeNote\FreeNoteBundle\Entity\Comment
            thread: FreeNote\FreeNoteBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread: fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote: fos_comment.acl.vote.roles
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN

mopa_bootstrap:
    navbar: ~
    form:
        render_required_asterisk: true
        render_optional_text: false

sylius_assortment:
    driver: doctrine/orm
    classes:
        product:
            model: FreeNote\FreeNoteBundle\Entity\Product
            controller: FreeNote\FreeNoteBundle\Controller\ProductController
            repository: FreeNote\FreeNoteBundle\Repository\ProductRepository
            form: FreeNote\FreeNoteBundle\Form\Type\ProductType
        variant:
            model: FreeNote\FreeNoteBundle\Entity\Variant
            form: FreeNote\FreeNoteBundle\Form\Type\VariantType

sylius_categorizer:
    driver: doctrine/orm
    catalogs:
        artykuly:
            property: "entries"
            model: FreeNote\FreeNoteBundle\Entity\ArticleCategory
            form:  free_note_article_category
            templates:
                backend: FreeNoteBundle:Backend/ArticleCategory:%s.html.twig
                frontend: FreeNoteBundle:Frontend/ArticleCategory:%s.html.twig
            pagination:
                mpp: 10
#        news:
#            property: "news"
#            model: FreeNote\FreeNoteBundle\Entity\PostCategory
#            templates:
#                backend: FreeNoteBundle:Backend/PostCategory:%s.html.twig
#                frontend: FreeNoteBundle:Frontend/PostCategory:%s.html.twig
#        events:
#            property: "events"
#            model: FreeNote\FreeNoteBundle\Entity\PostCategory
#            templates:
#                backend: FreeNoteBundle:Backend/PostCategory:%s.html.twig
#                frontend: FreeNoteBundle:Frontend/PostCategory:%s.html.twig
#        advertisements:
#            property: "advertisements"
#            model: FreeNote\FreeNoteBundle\Entity\PostCategory
#            templates:
#                backend: FreeNoteBundle:Backend/PostCategory:%s.html.twig
#                frontend: FreeNoteBundle:Frontend/PostCategory:%s.html.twig
    classes:
        controller:
            backend:
                category: FreeNote\FreeNoteBundle\Controller\Backend\fnCategoryController

sylius_cart:
    driver: doctrine/orm
    resolver: free_note_cart.resolver
    classes:
        cart:
            model: FreeNote\FreeNoteBundle\Entity\Cart
            repository: FreeNote\FreeNoteBundle\Repository\CartRepository
        item:
            model: FreeNote\FreeNoteBundle\Entity\CartItem
            form: FreeNote\FreeNoteBundle\Form\Type\CartItemType

sylius_blogger:
    driver: doctrine/orm
    classes:
        post:
            model: FreeNote\FreeNoteBundle\Entity\FakeEntity

sylius_sales:
    driver: doctrine/orm
    classes:
        order:
            model: FreeNote\FreeNoteBundle\Entity\Order
            form: FreeNote\FreeNoteBundle\Form\Type\OrderType
        order_item:
            model: FreeNote\FreeNoteBundle\Entity\OrderItem
            form: FreeNote\FreeNoteBundle\Form\Type\OrderItemType
        sellable:
            model: %sylius.model.variant.class%

sylius_addressing:
    driver: doctrine/orm

sylius_inventory:
    driver: doctrine/orm
    backorders: true
    classes:
        unit:
            model: FreeNote\FreeNoteBundle\Entity\InventoryUnit
        stockable:
            model: %sylius.model.variant.class%
    events:
        - sylius_assortment.product.pre_update
        - sylius_assortment.variant.pre_update

sylius_taxonomies:
    driver: doctrine/orm

sylius_taxation:
    driver: doctrine/orm
    classes:
        tax_rate:
            model: FreeNote\FreeNoteBundle\Entity\TaxRate
            form: FreeNote\FreeNoteBundle\Form\Type\TaxRateType

sylius_shipping:
    driver: doctrine/orm
    classes:
        shipment:
            model: FreeNote\FreeNoteBundle\Entity\Shipment
        shipment_item:
            model: FreeNote\FreeNoteBundle\Entity\InventoryUnit
        shipping_method:
            model: FreeNote\FreeNoteBundle\Entity\ShippingMethod
            form: FreeNote\FreeNoteBundle\Form\Type\ShippingMethodType

sylius_settings:
    driver: doctrine/orm

liip_doctrine_cache:
    namespaces:
        sylius_settings:
            type: %cache%

sylius_resource:
    resources:
        sylius.user:
            driver: doctrine/orm
            classes:
                model: FreeNote\FreeNoteBundle\Entity\User

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    textarea_class: "tinymce"
    language: %locale%
    theme:
        simple:
            theme: "advanced"
            theme_advanced_buttons1: "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink"
            theme_advanced_buttons2: ""
            theme_advanced_buttons3: ""
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            theme_advanced_statusbar_location: "bottom"
            plugins: "table,advhr, fullscreen"
            theme_advanced_buttons1_add: "table,advhr, fullscreen"
            paste_auto_cleanup_on_paste: true
        my:
            theme: "advanced"
            plugins: "imagemanager,table,save,advimage,pagebreak,paste"
            theme_advanced_enable: "table, forecolor, pagebreak"
            theme_advanced_buttons1 : "bold,forecolor,formatselect,removeformat,separator,outdent,indent,separator,bullist,table,pagebreak,charmap,separator,link,unlink,anchor,image"
            theme_advanced_buttons2 : "undo,redo,separator,removeformat,cleanup,help,code"
            theme_advanced_buttons3 : ""
            theme_advanced_more_colors : false
            theme_advanced_default_foreground_color : "#686868"
            theme_advanced_text_colors : "686868,3385B1"
            theme_advanced_blockformats : "Brak=div,Nagłówek1=h1,Nagłówek2=h2,Paragraf=p,Cytat=em"
            table_default_bordercolor: "#686868"
            paste_remove_styles: true
            paste_auto_cleanup_on_paste : true
            convert_urls : false


free_note:
    classes:
        article_entry:
            model: FreeNote\FreeNoteBundle\Entity\ArticleEntry
            type:  FreeNote\FreeNoteBundle\Form\Type\ArticleEntryType
            repository:  Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
            controller:  FreeNote\FreeNoteBundle\Controller\UploadableResourceController
