imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    default_locale:  %locale%
    form: ~
    secret:          %secret%
    csrf_protection:
        enabled: true
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    validation:      { enabled: true, enable_annotations: true }
    translator:      { fallback: %locale% }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    session:
        name: WN_SESSION
        lifetime: 72000


# Twig Configuration
twig:
    form:
        resources:
            - 'SyliusSandboxBundle::forms.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../web

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    FOSCommentBundle: ~
                    SyliusAddressingBundle: ~
                    SyliusAssortmentBundle: ~
                    SyliusBloggerBundle: ~
                    SyliusCartBundle: ~
                    SyliusCategorizerBundle: ~
                    SyliusInventoryBundle: ~
                    SyliusSalesBundle: ~
                    SyliusSettingsBundle: ~
                    SyliusShippingBundle: ~
                    SyliusTaxationBundle: ~
                    SyliusTaxonomiesBundle: ~
                    SyliusSandboxBundle: ~
#                    WnBundle: ~
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

# Swiftmailer Configuration
swiftmailer:
    disable_delivery: %kernel.debug%
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true

avalanche_imagine:
    source_root:  %kernel.root_dir%/../web
    web_root: %kernel.root_dir%/../web
    cache_prefix: media/cache
    filters:
        frontend_medium:
            type: thumbnail
            options: { size: [220, 180], mode: outbound }
        frontend_box:
            type: thumbnail
            options: { size: [130, 75], mode: outbound }
        backend_mini:
            type: thumbnail
            options: { size: [90, 60], mode: outbound }
        backend_medium:
            type: thumbnail
            options: { size: [250, 150], mode: outbound }

# User bundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Sylius\Bundle\SandboxBundle\Entity\User
#    user_class: Wn\WnBundle\Entity\WnUser

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Sylius\Bundle\SandboxBundle\Entity\Comment
            thread: Sylius\Bundle\SandboxBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread: fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote: fos_comment.acl.vote.roles
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN

mopa_bootstrap:
    navbar: ~

sylius_assortment:
    driver: doctrine/orm
    classes:
        product:
            model: Sylius\Bundle\SandboxBundle\Entity\Product
            controller: Sylius\Bundle\SandboxBundle\Controller\ProductController
            repository: Sylius\Bundle\SandboxBundle\Repository\ProductRepository
            form: Sylius\Bundle\SandboxBundle\Form\Type\ProductType
        variant:
            model: Sylius\Bundle\SandboxBundle\Entity\Variant
            form: Sylius\Bundle\SandboxBundle\Form\Type\VariantType

sylius_categorizer:
    driver: doctrine/orm
    catalogs:
        blog:
            property: "posts"
            model: Sylius\Bundle\SandboxBundle\Entity\PostCategory
            templates:
                backend: SyliusSandboxBundle:Backend/PostCategory:%s.html.twig
                frontend: SyliusSandboxBundle:Frontend/PostCategory:%s.html.twig

sylius_cart:
    driver: doctrine/orm
    resolver: sylius_sandbox_cart.resolver
    classes:
        cart:
            repository: Sylius\Bundle\SandboxBundle\Repository\CartRepository
        item:
            model: Sylius\Bundle\SandboxBundle\Entity\CartItem
            form: Sylius\Bundle\SandboxBundle\Form\Type\CartItemType

sylius_blogger:
    driver: doctrine/orm
    classes:
        post:
            model: Sylius\Bundle\SandboxBundle\Entity\Post
            form: Sylius\Bundle\SandboxBundle\Form\Type\PostType

sylius_sales:
    driver: doctrine/orm
    builder: sylius_sandbox.builder.order
    classes:
        order:
            model: Sylius\Bundle\SandboxBundle\Entity\Order
            form: Sylius\Bundle\SandboxBundle\Form\Type\OrderType
        item:
            model: Sylius\Bundle\SandboxBundle\Entity\OrderItem
            form: Sylius\Bundle\SandboxBundle\Form\Type\OrderItemType

sylius_addressing:
    driver: doctrine/orm

sylius_inventory:
    driver: doctrine/orm
    backorders: true
    classes:
        unit:
            model: Sylius\Bundle\SandboxBundle\Entity\InventoryUnit
        stockable:
            model: Sylius\Bundle\SandboxBundle\Entity\Variant
    events:
        - sylius_assortment.product.pre_update
        - sylius_assortment.variant.pre_update

sylius_taxonomies:
    driver: doctrine/orm
    classes:
        taxonomy:
            model: Sylius\Bundle\SandboxBundle\Entity\Taxonomy
        taxon:
            model: Sylius\Bundle\SandboxBundle\Entity\Taxon

sylius_taxation:
    driver: doctrine/orm
    rate_resolver: sylius_sandbox.tax_rate_resolver
    classes:
        rate:
            model: Sylius\Bundle\SandboxBundle\Entity\TaxRate
            form: Sylius\Bundle\SandboxBundle\Form\Type\TaxRateType

sylius_shipping:
    driver: doctrine/orm
    classes:
        method:
            model: Sylius\Bundle\SandboxBundle\Entity\ShippingMethod
            form: Sylius\Bundle\SandboxBundle\Form\Type\ShippingMethodType
        shipment:
            model: Sylius\Bundle\ShippingBundle\Entity\Shipment
        shipment_item:
            model: Sylius\Bundle\ShippingBundle\Entity\ShipmentItem

sylius_settings:
    driver: doctrine/orm

liip_doctrine_cache:
    namespaces:
        sylius_settings:
            type: %cache%

sylius_resource:
    resources:
        sylius_user.user:
            driver: doctrine/orm
            classes:
                model: Sylius\Bundle\SandboxBundle\Entity\User
