# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    FOSCommentBundle: ~
                    SyliusAddressingBundle: ~
                    SyliusAssortmentBundle: ~
                    SyliusBloggerBundle: ~
                    SyliusCartBundle: ~
                    SyliusCategorizerBundle: ~
                    SyliusInventoryBundle: ~
                    SyliusSalesBundle: ~
                    SyliusSettingsBundle: ~
                    SyliusShippingBundle: ~
                    SyliusTaxationBundle: ~
                    SyliusTaxonomiesBundle: ~
                    SyliusSandboxBundle: ~
                    WnWnBundle: ~
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
