security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_WRITER:      ROLE_USER
        ROLE_BUYER:       ROLE_USER
        ROLE_BUYER_CO:    ROLE_USER
        ROLE_SELLER:      ROLE_USER
        ROLE_ADMIN:       [ROLE_WRITER, ROLE_BUYER, ROLE_BUYER_CO, ROLE_SELLER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login
                use_referer: true
            remember_me:
                key: eUodAjYEzDza72
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: ROLE_WRITER }
