sylius_sales_backend_order:
    resource: @SyliusSalesBundle/Resources/config/routing/backend/order.yml
    prefix: /administration/orders

sylius_sales_backend_status:
    resource: @SyliusSalesBundle/Resources/config/routing/backend/status.yml
    prefix: /administration/orders/statuses

sylius_sandbox_checkout_start:
    pattern: /checkout
    defaults: { _controller: sylius_flow.controller.process:startAction, scenarioAlias: 'sylius_sandbox_checkout' }

sylius_sandbox_checkout_display:
    pattern: /checkout/{stepName}
    defaults: { _controller: sylius_flow.controller.process:displayAction, scenarioAlias: 'sylius_sandbox_checkout' }

sylius_sandbox_checkout_forward:
    pattern: /checkout/{stepName}/forward
    defaults: { _controller: sylius_flow.controller.process:forwardAction, scenarioAlias: 'sylius_sandbox_checkout' }
