free_note_backend_address_list:
    pattern: /list
    defaults:
        _controller: sylius.controller.address:indexAction
        _template: FreeNoteBundle:Backend/Address:list.html.twig
        _sortable: true
        _sorting:
            updatedAt: desc

free_note_backend_address_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.address:createAction
        _template: FreeNoteBundle:Backend/Address:create.html.twig
        _redirect: free_note_backend_address_show

free_note_backend_address_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.address:updateAction
        _template: FreeNoteBundle:Backend/Address:update.html.twig
        _redirect: free_note_backend_address_show

free_note_backend_address_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.address:deleteAction
        _redirect: free_note_backend_address_list

free_note_backend_address_show:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.address:showAction
        _template: FreeNoteBundle:Backend/Address:show.html.twig
