free_note_backend_advertisement_entry_list:
    pattern: /
    defaults:
        _controller: free_note.controller.advertisement_entry:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/AdvertisementEntry:list.html.twig
            filterable: true
            sortable: true
            sorting:
                createdAt: desc

free_note_backend_advertisement_entry_create:
    pattern: /create
    defaults:
        _controller: free_note.controller.advertisement_entry:createAction
        _sylius:
            template: FreeNoteBundle:Backend/AdvertisementEntry:create.html.twig
            redirect: free_note_backend_advertisement_entry_show

free_note_backend_advertisement_entry_update:
    pattern: /{id}/update
    defaults:
        _controller: free_note.controller.advertisement_entry:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/AdvertisementEntry:update.html.twig
            redirect: free_note_backend_advertisement_entry_show

free_note_backend_advertisement_entry_delete:
    pattern: /{id}/delete
    defaults:
        _controller: free_note.controller.advertisement_entry:deleteAction
        _sylius:
            redirect: free_note_backend_advertisement_entry_list

free_note_backend_advertisement_entry_show:
    pattern: /{id}
    defaults:
        _controller: free_note.controller.advertisement_entry:showAction
        _sylius:
            template: FreeNoteBundle:Backend/AdvertisementEntry:show.html.twig
