free_note_backend_article_entry_list:
    pattern: /
    defaults:
        _controller: free_note.controller.article_entry:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/ArticleEntry:list.html.twig
            filterable: true
            sortable: true
            sorting:
                createdAt: desc

free_note_backend_article_entry_create:
    pattern: /create
    defaults:
        _controller: free_note.controller.article_entry:createAction
        _sylius:
            template: FreeNoteBundle:Backend/ArticleEntry:create.html.twig
            redirect: free_note_backend_article_entry_show

free_note_backend_article_entry_update:
    pattern: /{id}/update
    defaults:
        _controller: free_note.controller.article_entry:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/ArticleEntry:update.html.twig
            redirect: free_note_backend_article_entry_show

free_note_backend_article_entry_delete:
    pattern: /{id}/delete
    defaults:
        _controller: free_note.controller.article_entry:deleteAction
        _sylius:
            redirect: free_note_backend_article_entry_list

free_note_backend_article_entry_show:
    pattern: /{id}
    defaults:
        _controller: free_note.controller.article_entry:showAction
        _sylius:
            template: FreeNoteBundle:Backend/ArticleEntry:show.html.twig
