free_note_backend_option_list:
    pattern: /
    defaults:
        _controller: sylius.controller.option:indexAction
        template: FreeNoteBundle:Backend/Option:list.html.twig
        sortable: true
        sorting:
            name: desc

free_note_backend_option_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.option:createAction
        template: FreeNoteBundle:Backend/Option:create.html.twig
        redirect: free_note_backend_option_list

free_note_backend_option_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.option:updateAction
        template: FreeNoteBundle:Backend/Option:update.html.twig
        redirect: free_note_backend_option_list

free_note_backend_option_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.option:deleteAction
        redirect: free_note_backend_option_list
