free_note_backend_option_list:
    pattern: /
    defaults:
        _controller: sylius.controller.option:indexAction
        _template: FreeNoteBundle:Backend/Option:list.html.twig
        _sortable: true
        _sorting:
            name: desc

free_note_backend_option_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.option:createAction
        _template: FreeNoteBundle:Backend/Option:create.html.twig
        _redirect: free_note_backend_option_list

free_note_backend_option_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.option:updateAction
        _template: FreeNoteBundle:Backend/Option:update.html.twig
        _redirect: free_note_backend_option_list

free_note_backend_option_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.option:deleteAction
        _redirect: free_note_backend_option_list
