free_note_backend_post_list:
    pattern: /
    defaults:
        _controller: sylius_blogger.controller.post:indexAction
        _template: FreeNoteBundle:Backend/Post:list.html.twig

free_note_backend_post_create:
    pattern: /create
    defaults:
        _controller: sylius_blogger.controller.post:createAction
        _template: FreeNoteBundle:Backend/Post:create.html.twig
        _redirect: free_note_backend_post_show

free_note_backend_post_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius_blogger.controller.post:updateAction
        _template: FreeNoteBundle:Backend/Post:update.html.twig
        _redirect: free_note_backend_post_show

free_note_backend_post_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_blogger.controller.post:deleteAction
        _redirect: free_note_backend_post_list

free_note_backend_post_show:
    pattern: /{id}
    defaults:
        _controller: sylius_blogger.controller.post:showAction
        _template: FreeNoteBundle:Backend/Post:show.html.twig
