free_note_backend_product_list:
    pattern: /
    defaults:
        _controller: sylius.controller.product:indexAction
        _template: FreeNoteBundle:Backend/Product:list.html.twig
        _sortable: true
        _sorting:
            updatedAt: desc

free_note_backend_product_list_by_taxon:
    pattern: /t/{permalink}
    defaults:
        _controller: sylius.controller.product:listByTaxonAction
        _template: FreeNoteBundle:Backend/Product:listByTaxon.html.twig

free_note_backend_product_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.product:createAction
        _template: FreeNoteBundle:Backend/Product:create.html.twig
        _redirect: free_note_backend_product_show

free_note_backend_product_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.product:updateAction
        _template: FreeNoteBundle:Backend/Product:update.html.twig
        _redirect: free_note_backend_product_show

free_note_backend_product_update_variants:
    pattern: /{id}/update-variants
    defaults:
        _controller: sylius.controller.product:updateAction
        _form: free_note_product_variants_grid
        _template: FreeNoteBundle:Backend/Product:updateVariants.html.twig
        _redirect: free_note_backend_product_show

free_note_backend_product_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.product:deleteAction
        _redirect: free_note_backend_product_list

free_note_backend_product_duplicate:
    pattern: /{id}/duplicate
    defaults:
        _controller: sylius.controller.product:duplicateAction

free_note_backend_product_show:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.product:showAction
        _template: FreeNoteBundle:Backend/Product:show.html.twig
