free_note_backend_product_list:
    pattern: /
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/Product:list.html.twig
            sortable: true
            sorting:
                updatedAt: desc

free_note_backend_product_list_by_taxon:
    pattern: /t/{permalink}
    defaults:
        _controller: sylius.controller.product:listByTaxonAction
        _sylius:
            template: FreeNoteBundle:Backend/Product:listByTaxon.html.twig

free_note_backend_product_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            template: FreeNoteBundle:Backend/Product:create.html.twig
            redirect: free_note_backend_product_show

free_note_backend_product_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/Product:update.html.twig
            redirect: free_note_backend_product_show

free_note_backend_product_update_variants:
    pattern: /{id}/update-variants
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            form: free_note_product_variants_grid
            template: FreeNoteBundle:Backend/Product:updateVariants.html.twig
            redirect: free_note_backend_product_show

free_note_backend_product_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.product:deleteAction
        _sylius:
            redirect: free_note_backend_product_list

free_note_backend_product_duplicate:
    pattern: /{id}/duplicate
    defaults:
        _controller: sylius.controller.product:duplicateAction

free_note_backend_product_show:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            template: FreeNoteBundle:Backend/Product:show.html.twig
