free_note_backend_property_list:
    pattern: /
    defaults:
        _controller: sylius.controller.property:indexAction
        template: FreeNoteBundle:Backend/Property:list.html.twig
        sortable: true
        sorting:
            name: desc

free_note_backend_property_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.property:createAction
        template: FreeNoteBundle:Backend/Property:create.html.twig
        redirect: free_note_backend_property_list

free_note_backend_property_update:
    pattern: /update
    defaults:
        _controller: sylius.controller.property:updateAction
        template: FreeNoteBundle:Backend/Property:update.html.twig
        redirect: free_note_backend_property_list

free_note_backend_property_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.property:deleteAction
        redirect: free_note_backend_property_list
