free_note_backend_province_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.province:createAction
        _sylius:
            template: FreeNoteBundle:Backend/Province:create.html.twig
            redirect: free_note_backend_country_list

free_note_backend_province_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.province:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/Province:update.html.twig
            redirect: free_note_backend_country_list

free_note_backend_province_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.province:deleteAction
        _sylius:
            redirect: free_note_backend_country_list
