free_note_backend_shipping_category_list:
    pattern: /
    defaults:
        _controller: sylius.controller.category:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/ShippingCategory:list.html.twig
            sortable: true
            sorting:
                name: desc

free_note_backend_shipping_category_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.category:createAction
        _sylius:
            template: FreeNoteBundle:Backend/ShippingCategory:create.html.twig
            redirect: free_note_backend_shipping_category_list

free_note_backend_shipping_category_update:
    pattern: /update
    defaults:
        _controller: sylius.controller.category:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/ShippingCategory:update.html.twig
            redirect: free_note_backend_shipping_category_list

free_note_backend_shipping_category_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.category:deleteAction
        _sylius:
            redirect: free_note_backend_shipping_category_list
