free_note_backend_shipping_category_list:
    pattern: /
    defaults:
        _controller: sylius.controller.category:indexAction
        template: FreeNoteBundle:Backend/ShippingCategory:list.html.twig
        sortable: true
        sorting:
            name: desc

free_note_backend_shipping_category_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.category:createAction
        template: FreeNoteBundle:Backend/ShippingCategory:create.html.twig
        redirect: free_note_backend_shipping_category_list

free_note_backend_shipping_category_update:
    pattern: /update
    defaults:
        _controller: sylius.controller.category:updateAction
        template: FreeNoteBundle:Backend/ShippingCategory:update.html.twig
        redirect: free_note_backend_shipping_category_list

free_note_backend_shipping_category_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.category:deleteAction
        redirect: free_note_backend_shipping_category_list
