free_note_backend_stockable_list:
    pattern: /list
    defaults:
        _controller: sylius.controller.stockable:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/Stockable:list.html.twig
            sortable: true
            sorting:
                updatedAt: asc
