free_note_backend_stockable_list:
    pattern: /list
    defaults:
        _controller: sylius.controller.stockable:indexAction
        _template: FreeNoteBundle:Backend/Stockable:list.html.twig
        _sortable: true
        _sorting:
            updatedAt: asc
