free_note_backend_tax_rate_list:
    pattern: /
    defaults:
        _controller: sylius.controller.tax_rate:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/TaxRate:list.html.twig
            sortable: true
            sorting:
                name: desc

free_note_backend_tax_rate_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.tax_rate:createAction
        _sylius:
            template: FreeNoteBundle:Backend/TaxRate:create.html.twig
            redirect: free_note_backend_tax_rate_list

free_note_backend_tax_rate_update:
    pattern: /update
    defaults:
        _controller: sylius.controller.tax_rate:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/TaxRate:update.html.twig
            redirect: free_note_backend_tax_rate_list

free_note_backend_tax_rate_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.tax_rate:deleteAction
        _sylius:
            redirect: free_note_backend_tax_rate_list
