free_note_backend_tax_category_list:
    pattern: /
    defaults:
        _controller: sylius.controller.tax_category:indexAction
        _template: FreeNoteBundle:Backend/TaxCategory:list.html.twig
        _sortable: true
        _sorting:
            name: desc

free_note_backend_tax_category_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.tax_category:createAction
        _template: FreeNoteBundle:Backend/TaxCategory:create.html.twig
        _redirect: free_note_backend_tax_category_list

free_note_backend_tax_category_update:
    pattern: /update
    defaults:
        _controller: sylius.controller.tax_category:updateAction
        _template: FreeNoteBundle:Backend/TaxCategory:update.html.twig
        _redirect: free_note_backend_tax_category_list

free_note_backend_tax_category_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.tax_category:deleteAction
        _redirect: free_note_backend_tax_category_list
