free_note_backend_tax_rate_list:
    pattern: /
    defaults:
        _controller: sylius.controller.tax_rate:indexAction
        _template: FreeNoteBundle:Backend/TaxRate:list.html.twig
        _sortable: true
        _sorting:
            name: desc

free_note_backend_tax_rate_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.tax_rate:createAction
        _template: FreeNoteBundle:Backend/TaxRate:create.html.twig
        _redirect: free_note_backend_tax_rate_list

free_note_backend_tax_rate_update:
    pattern: /update
    defaults:
        _controller: sylius.controller.tax_rate:updateAction
        _template: FreeNoteBundle:Backend/TaxRate:update.html.twig
        _redirect: free_note_backend_tax_rate_list

free_note_backend_tax_rate_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.tax_rate:deleteAction
        _redirect: free_note_backend_tax_rate_list
