free_note_backend_taxon_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.taxon:createAction
        _template: FreeNoteBundle:Backend/Taxon:create.html.twig
        _redirect: free_note_backend_taxonomy_list

free_note_backend_taxon_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.taxon:updateAction
        _template: FreeNoteBundle:Backend/Taxon:update.html.twig
        _redirect: free_note_backend_taxonomy_list

free_note_backend_taxon_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.taxon:deleteAction
        _redirect: free_note_backend_taxonomy_list
