free_note_backend_taxonomy_list:
    pattern: /list
    defaults:
        _controller: sylius.controller.taxonomy:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/Taxonomy:list.html.twig
            sortable: true

free_note_backend_taxonomy_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.taxonomy:createAction
        _sylius:
            template: FreeNoteBundle:Backend/Taxonomy:create.html.twig
            redirect: free_note_backend_taxonomy_list

free_note_backend_taxonomy_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.taxonomy:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/Taxonomy:update.html.twig
            redirect: free_note_backend_taxonomy_list

free_note_backend_taxonomy_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.taxonomy:deleteAction
        _sylius:
            redirect: free_note_backend_taxonomy_list
