free_note_backend_user_list:
    pattern: /list
    defaults:
        _controller: sylius.controller.user:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/User:list.html.twig
            filterable: true
            sortable: true
            sorting:
                id: desc

free_note_backend_user_register:
    pattern: /register/{who}
    defaults:
        _controller: FreeNoteBundle:Backend/User:register

free_note_backend_user_registration_confirmed:
    pattern: /confirmed
    defaults:
        _controller: FreeNoteBundle:Backend/User:confirmed
        requirements:
            _method: GET

free_note_backend_user_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.user:deleteAction
        _sylius:
            redirect: free_note_backend_user_list

free_note_backend_user_show:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.user:showAction
        _sylius:
            template: FreeNoteBundle:Backend/User:show.html.twig
