free_note_backend_user_list:
    pattern: /list
    defaults:
        _controller: sylius.controller.user:indexAction
        _template: FreeNoteBundle:Backend/User:list.html.twig
        _filterable: true
        _sortable: true
        _sorting:
            id: desc

free_note_backend_user_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.user:deleteAction
        _redirect: free_note_backend_user_list

free_note_backend_user_show:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.user:showAction
        _template: FreeNoteBundle:Backend/User:show.html.twig
