free_note_backend_variant_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.variant:createAction
        _sylius:
            template: FreeNoteBundle:Backend/Variant:create.html.twig
            redirect: free_note_backend_variant_show

free_note_backend_variant_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.variant:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/Variant:update.html.twig
            redirect: free_note_backend_variant_show

free_note_backend_variant_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.variant:deleteAction
        _sylius:
            redirect: free_note_backend_product_list

free_note_backend_variant_generate:
    pattern: /generate
    defaults:
        _controller: sylius.controller.variant:generateAction
        _sylius:
            redirect: free_note_backend_product_show

free_note_backend_variant_show:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.variant:showAction
        _sylius:
            template: FreeNoteBundle:Backend/Variant:show.html.twig
            productId: 'any' # Hacky hack...
