free_note_backend_zone_list:
    pattern: /
    defaults:
        _controller: sylius.controller.zone:indexAction
        _sylius:
            template: FreeNoteBundle:Backend/Zone:list.html.twig

free_note_backend_zone_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.zone:createAction
        _sylius:
            template: FreeNoteBundle:Backend/Zone:create.html.twig
            redirect: free_note_backend_zone_list

free_note_backend_zone_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.zone:updateAction
        _sylius:
            template: FreeNoteBundle:Backend/Zone:update.html.twig
            redirect: free_note_backend_zone_list

free_note_backend_zone_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.zone:deleteAction
        _sylius:
            redirect: free_note_backend_zone_list
