free_note_category_show:
    pattern: /{alias}/kategorie/{slug}
    defaults:
        _controller: free_note.controller.article_entry:indexAction
        _sylius:
            template: FreeNoteBundle:Frontend/ArticleEntry:list.html.twig
            paginate: 10
            filterable: true
            sortable: true
            criteria:
                published: true
            sorting:
                createdAt: desc
