free_note_post_list:
    pattern: /
    defaults:
        _controller: sylius_blogger.controller.post:indexAction
        template: FreeNoteBundle:Frontend/Post:list.html.twig
        paginate: 10
        criteria:
            published: true
        sorting:
            createdAt: desc

free_note_post_show:
    pattern: /{slug}
    defaults:
        _controller: sylius_blogger.controller.post:showAction
        template: FreeNoteBundle:Frontend/Post:show.html.twig
        identifier: slug
